project:
  type: book
  output-dir: docs

# execute: 
#   freeze: auto

language:
  section-title-appendices: "Apêndices"

book:
  title: "IRIS -- Indicadores Rodoviários Integrados de Segurança"
  subtitle: "Produto 04 -- Relatório Final"
  author: 
  - name: Pedro Augusto Borges dos Santos
  - name: Paloma Hellen Pereira Eleuterio
  - name: Dara de César Borszcz
  - name: Dr. Jorge Tiago Bastos
  date: 2025-01-09
  output-file: "report_04"
  chapters:
    - index.qmd
    - 04_01_introducao.qmd
    - 04_02_revisao.qmd
    - 04_03_metodologia.qmd
    - 04_04_resultados.qmd
    - 04_05_conclusoes.qmd
    - 99_references.qmd
  appendices:
    # - 02_9a_mapas.qmd
    - 04_9b_padronizacao.qmd
    - 04_9c_inversao.qmd
  
  # twitter-card: true
  repo-url: https://www.github.com/onsv/indicadores-seg-viaria
  # cover-image: logo/capa.png
  language: pt-BR
  # favicon: logo/onsv-fav.ico

bibliography: references.bib

# csl: apa

format:
  pdf:
    documentclass: report
    lang: pt-BR
    lof: true
    lot: true
    toc-depth: 4
    fig-dpi: 300
    fig-pos: "H"
    echo: false
    fontsize: 11pt
    linkcolor: "black"
    toccolor: "black"
    citecolor: "black"
    link-citations: true
    warning: false
    geometry: 
    - right=30mm
    - left=30mm
    - bottom=30mm
    - top=30mm
    papersize: a4
    cap-location: top
    # cite-method: biblatex
    csl: apa.csl
    include-in-header: 
      text: |
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \usepackage[x11names]{xcolor}
        \usepackage{sectsty}

        \definecolor{onsvblue}{HTML}{00496D}

        \chapterfont{\color{onsvblue}}    
        \sectionfont{\color{onsvblue}}     
        \subsectionfont{\color{onsvblue}}
        \subsubsectionfont{\color{onsvblue}}
  docx:
    number-sections: true
    warning: false
    echo: false
    toc: true
    lang: pt-BR
    fig-dpi: 300
    papersize: a4
    cap-location: top