# Introdução {#sec-intro}

Os sinistros de trânsito são a causa de quase 1,2 milhões de óbitos anuais em todo o mundo. Os ferimentos que ocorrem nestes eventos são a principal causa de mortes na faixa etária entre 5 e 29 anos. Nove em cada dez óbitos ocorrem em países de baixa e média renda [@whoGlobalStatusReport2023]. No Brasil, as últimas estatísticas oficiais mostram quase 34 mil óbitos por ano em consequência de sinistros no trânsito [@ministeriodasaudeSistemaInformacoesMortalidade2022].

Visto o cenário da sinistralidade no Brasil, O Plano Nacional de Mortes e Lesões no Trânsito (Pnatrans) foi desenvolvido em 2018 como uma política pública estruturante no contexto da segurança viária. O Plano nasceu com a principal meta de reduzir pela metade a quantidade de lesões e mortes no trânsito até o ano de 2028 [@brasilCriaPlanoNacional2018]. O acompanhamento do desempenho da segurança viária necessita o desenvolvimento e acompanhamento de indicadores, indo além daqueles que medem apenas a quantidade de mortes, lesões e sinistros [@santosPlanoNacionalReducao2023].

Neste contexto, o projeto Indicadores Rodoviários Integrados de Segurança - IRIS - visa criar indicadores de desempenho da segurança viária para diagnosticar o desempenho das unidades da federação nos seis pilares do atual Pnatrans: (I) Gestão da Segurança no Trânsito; (II) Vias Seguras; (III) Segurança Veicular; (IV) Educação para o Trânsito; (V) Vigilância; Promoção da Saúde e Atendimento às Vítimas; e (VI) Normatização e Fiscalização. Esse projeto tem como base o trabalho sobre indicadores de desempenho elaborado anteriormente por @borszczINDICADORESDESEMPENHOSEGURANCA2023a e também de inspira no PIN - *The Road Safety Performance Index*, uma iniciativa do *European Transport Safety Council* que compara o desempenho entre os países-membros da União Europeia [@etscPINRoadSafety2024].

O presente documento apresenta a primeira etapa do projeto, contendo a metodologia de coleta nas fontes oficiais brasileiras e a construção dos indicadores de segurança viária para cada pilar do Pnatrans. Em sequência da introdução, o @sec-revbib contém a revisão bibliográfica e o @sec-method contém a metodologia do trabalho. Por fim, o @sec-results apresenta os resultados preliminares dos indicadores calculados e o @sec-conclusoes apresenta as conclusões.
