---
editor_options: 
  chunk_output_type: console
---
# Padronização dos indicadores {#sec-padronizacao}

```{r}
#| label: setup
#| include: false

library(
    targets, 
    lib.loc = here::here("renv/library/macos/R-4.4/aarch64-apple-darwin20/")
)
library(
    tidyverse,
    lib.loc = here::here("renv/library/macos/R-4.4/aarch64-apple-darwin20/")
)
library(gt)

```

```{r}
#| label: tbl-scaled-pilar1
#| tbl-cap: Valores padronizados dos indicadores do Pilar I
#| echo: false

tar_read(indicadores_scaled, store = here::here("_targets")) |> 
    select(-cod_uf) |> 
    filter(str_extract(indicador, "^[^.]+\\.") == "i.") |> 
    pivot_wider(
        names_from = indicador,
        values_from = c(valor, valor_padronizado)
    ) |>
    group_by(regiao_uf) |> 
    gt() |> 
    fmt_number(decimals = 2, dec_mark = ",", sep_mark = ".") |> 
    fmt_percent(
        columns = valor_i.1:valor_i.2,
        decimals = 2, dec_mark = ",",
        sep_mark = "."
    ) |> 
    tab_spanner(
        columns = valor_i.1:valor_i.4,
        label = "Valor original"
    ) |> 
    tab_spanner(
        columns = valor_padronizado_i.1:valor_padronizado_i.4,
        label = "Valor padronizado"
    ) |> 
    cols_label(
        valor_i.1 = "I.1",
        valor_i.2 = "I.2",
        valor_i.3 = "I.3",
        valor_i.4 = "I.4",
        valor_padronizado_i.1 = "I.1",
        valor_padronizado_i.2 = "I.2",
        valor_padronizado_i.3 = "I.3",
        valor_padronizado_i.4 = "I.4",
        nome_uf = "UF"
    ) |> 
    tab_options(table.font.size = "8pt")
```

\newpage

```{r}
#| label: tbl-scaled-pilar2
#| tbl-cap: Valores padronizados dos indicadores do Pilar II
#| echo: false

tar_read(indicadores_scaled, store = here::here("_targets")) |> 
    select(-cod_uf) |> 
    filter(str_extract(indicador, "^[^.]+\\.") == "ii.") |> 
    rename(original = valor, padronizado = valor_padronizado) |>
    pivot_wider(
        names_from = indicador,
        values_from = c(original, padronizado)
    ) |>
    group_by(regiao_uf) |> 
    gt() |> 
    fmt_number(
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    fmt_percent(
        columns = starts_with("original"),
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    tab_spanner(
        columns = starts_with("original"),
        label = "Valor original"
    ) |> 
    tab_spanner(
        columns = starts_with("padronizado"),
        label = "Valor padronizado"
    ) |> 
    cols_label(
        original_ii.1 = "II.1",
        original_ii.2 = "II.2",
        original_ii.3 = "II.3",
        original_ii.4 = "II.4",
        original_ii.5 = "II.5",
        padronizado_ii.1 = "II.1",
        padronizado_ii.2 = "II.2",
        padronizado_ii.3 = "II.3",
        padronizado_ii.4 = "II.4",
        padronizado_ii.5 = "II.5",
        nome_uf = "UF"
    ) |> 
    tab_options(table.font.size = "8pt")
```

\newpage

```{r}
#| label: tbl-scaled-pilar3
#| tbl-cap: Valores padronizados dos indicadores do Pilar III
#| echo: false

tar_read(indicadores_scaled, store = here::here("_targets")) |> 
    select(-cod_uf) |> 
    filter(str_extract(indicador, "^[^.]+\\.") == "iii.") |> 
    rename(original = valor, padronizado = valor_padronizado) |>
    pivot_wider(
        names_from = indicador,
        values_from = c(original, padronizado)
    ) |>
    group_by(regiao_uf) |> 
    gt() |> 
    fmt_number(
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    fmt_percent(
        columns = starts_with("original"),
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    tab_spanner(
        columns = starts_with("original"),
        label = "Valor original"
    ) |> 
    tab_spanner(
        columns = starts_with("padronizado"),
        label = "Valor padronizado"
    ) |> 
    cols_label(
        original_iii.1 = "III.1",
        original_iii.2 = "III.2",
        original_iii.3 = "III.3",
        original_iii.4 = "III.4",
        padronizado_iii.1 = "III.1",
        padronizado_iii.2 = "III.2",
        padronizado_iii.3 = "III.3",
        padronizado_iii.4 = "III.4",
        nome_uf = "UF"
    ) |> 
    tab_options(table.font.size = "10pt")
```

\newpage

\blandscape

```{r}
#| label: tbl-scaled-pilar4
#| tbl-cap: Valores padronizados dos indicadores do Pilar IV
#| echo: false

tar_read(indicadores_scaled, store = here::here("_targets")) |> 
    select(-cod_uf) |> 
    filter(str_extract(indicador, "^[^.]+\\.") == "iv.") |> 
    rename(original = valor, padronizado = valor_padronizado) |>
    pivot_wider(
        names_from = indicador,
        values_from = c(original, padronizado)
    ) |>
    group_by(regiao_uf) |> 
    gt() |> 
    fmt_number(
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    tab_spanner(
        columns = starts_with("original"),
        label = "Valor original"
    ) |> 
    tab_spanner(
        columns = starts_with("padronizado"),
        label = "Valor padronizado"
    ) |> 
    cols_label(
        original_iv.1 = "IV.1",
        original_iv.2 = "IV.2",
        original_iv.3 = "IV.3",
        original_iv.4 = "IV.4",
        original_iv.5 = "IV.5",
        original_iv.6 = "IV.6",
        original_iv.7 = "IV.7",
        padronizado_iv.1 = "IV.1",
        padronizado_iv.2 = "IV.2",
        padronizado_iv.3 = "IV.3",
        padronizado_iv.4 = "IV.4",
        padronizado_iv.5 = "IV.5",
        padronizado_iv.6 = "IV.6",
        padronizado_iv.7 = "IV.7",
        nome_uf = "UF"
    ) |> 
    tab_options(table.font.size = "8pt")
```

\elandscape

```{r}
#| label: tbl-scaled-pilar5
#| tbl-cap: Valores padronizados dos indicadores do Pilar V
#| echo: false

tar_read(indicadores_scaled, store = here::here("_targets")) |> 
    select(-cod_uf) |> 
    filter(str_extract(indicador, "^[^.]+\\.") == "v.") |> 
    rename(original = valor, padronizado = valor_padronizado) |>
    pivot_wider(
        names_from = indicador,
        values_from = c(original, padronizado)
    ) |>
    group_by(regiao_uf) |> 
    gt() |> 
    fmt_number(
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    tab_spanner(
        columns = starts_with("original"),
        label = "Valor original"
    ) |> 
    tab_spanner(
        columns = starts_with("padronizado"),
        label = "Valor padronizado"
    ) |> 
    cols_label(
        original_v.1 = "V.I",
        original_v.2 = "V.2",
        original_v.3 = "V.3",
        original_v.4 = "V.4",
        padronizado_v.1 = "V.1",
        padronizado_v.2 = "V.2",
        padronizado_v.3 = "V.3",
        padronizado_v.4 = "V.4",
        nome_uf = "UF"
    ) |> 
    tab_options(table.font.size = "10pt")
```

\newpage

\blandscape

```{r}
#| label: tbl-scaled-pilar6
#| tbl-cap: Valores padronizados dos indicadores do Pilar VI
#| echo: false

tar_read(indicadores_scaled, store = here::here("_targets")) |> 
    select(-cod_uf) |> 
    filter(str_extract(indicador, "^[^.]+\\.") == "vi.") |> 
    rename(original = valor, padronizado = valor_padronizado) |>
    pivot_wider(
        names_from = indicador,
        values_from = c(original, padronizado)
    ) |>
    #select(nome_uf, regiao_uf, starts_with("original"),) |> 
    group_by(regiao_uf) |> 
    gt() |> 
    fmt_number(
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    tab_spanner(
        columns = starts_with("original"),
        label = "Valor original"
    ) |> 
    tab_spanner(
        columns = starts_with("padronizado"),
        label = "Valor padronizado"
    ) |> 
    cols_label(
        original_vi.1 = "VI.1",
        original_vi.2 = "VI.2",
        original_vi.3 = "VI.3",
        original_vi.4 = "VI.4",
        original_vi.5 = "VI.5",
        original_vi.6 = "VI.6",
        original_vi.7 = "VI.7",
        padronizado_vi.1 = "VI.1",
        padronizado_vi.2 = "VI.2",
        padronizado_vi.3 = "VI.3",
        padronizado_vi.4 = "VI.4",
        padronizado_vi.5 = "VI.5",
        padronizado_vi.6 = "VI.6",
        padronizado_vi.7 = "VI.7",
        # original_vi.08 = "VI.08",
        # original_vi.09 = "VI.09",
        # original_vi.10 = "VI.10",
        # original_vi.11 = "VI.11",
        # original_vi.12 = "VI.12",
        nome_uf = "UF"
    ) |> 
    tab_options(table.font.size = "8pt")
```

\elandscape

```{r}
#| label: tbl-scaled-resultados
#| tbl-cap: Valores padronizados dos indicadores de resultado
#| echo: false

tar_read(indicadores_scaled, store = here::here("_targets")) |> 
    select(-cod_uf) |> 
    filter(str_extract(indicador, "^[^.]+\\.") == "0.") |> 
    rename(original = valor, padronizado = valor_padronizado) |>
    pivot_wider(
        names_from = indicador,
        values_from = c(original, padronizado)
    ) |>
    group_by(regiao_uf) |> 
    gt() |> 
    fmt_number(
        decimals = 2, 
        dec_mark = ",",
        sep_mark = "."
    ) |> 
    tab_spanner(
        columns = starts_with("original"),
        label = "Valor original"
    ) |> 
    tab_spanner(
        columns = starts_with("padronizado"),
        label = "Valor padronizado"
    ) |> 
    cols_label(
        original_0.1 = "0.1",
        original_0.2 = "0.2",
        original_0.3 = "0.3",
        padronizado_0.1 = "0.1",
        padronizado_0.2 = "0.2",
        padronizado_0.3 = "0.3",
        nome_uf = "UF"
    ) |> 
    tab_options(table.font.size = "10pt")
```
